.travis.yml, CMakeLists.txt, README.md, scripts/travis_target.sh
Add coveralls.io integration and CI status badges. Measures code coverage on unit test runs in Travis CI using gcov; unity builds on Travis are reverted to allow for code coverage reporting.
=> (maint) Add coveralls.io integration

lib/src/facts/posix/collection.cc
This commit updates the default search directory for external facts.
We now look in `/opt/puppetlabs/agent/facts.d` for both open source and
PE versions of Facter. Note that this change only affects Unix agents,
as Windows paths are staying the same.
This change is part of the unified agent effort.
=> (CFACT-150) Update default external fact directory for unified agent layout

contrib/cfacter.ps1
Only set $env:TEMP if it's not already a valid location (this allows it to
be used for CI while still working for ad-hoc usage). Also use shorter
sourceforge download URL.
=> (maint) Cleanup Powershell build script

.travis.yml, CMakeLists.txt
cppcheck still exits with status 0 if there are errors. Add an option to
return status 2 if cppcheck found errors.
=> (maint) Make cppcheck use exitcode

.travis.yml
Eliminate longest extraneous build steps from Travis CI.
=> (maint) Use pre-compiled doxygen and yaml-cpp

CMakeLists.txt, lib/src/execution/posix/execution.cc, lib/src/execution/windows/execution.cc, lib/src/facts/external/json_resolver.cc, lib/src/facts/linux/virtualization_resolver.cc, lib/src/facts/resolvers/gce_resolver.cc, lib/src/facts/solaris/zpool_resolver.cc, lib/src/facts/zfs/zpool_resolver.cc
This commit enables warnings in cppcheck and addresses some warnings and
style errors (including one bug) that was found by cppcheck.
The bug addressed was that openvz detection was always returning an
empty string.
=> (maint) Fix cppcheck warnings.

exe/cfacter.cc, lib/inc/facter/ruby/api.hpp, lib/src/facts/posix/uptime_resolver.cc, lib/src/ruby/api.cc, lib/tests/main.cc
Catch all exceptions, initialize variables, and ensure no integer
truncation when returning size_t.
=> (maint) Fixes for Coverity Scan issues

gem/Gemfile, gem/cfacter.gemspec
Ruby 2.1.5 requires ffi 1.9.5+; we use ffi 1.9.6 in most cases. Update
the gem and Gemfile to reflect those versions.
=> (CFACT-178) Update FFI version

lib/src/util/windows/registry.cc, lib/src/util/windows/wmi.cc, lib/tests/util/windows/environment.cc
A few Windows-related types have invalid, self-delegating constructors.
There's a signed/unsigned mismatch in one Windows-related test.
=> (maint) Fix Windows build errors under GCC 4.9.

ext/redhat/cfacter.spec.erb
This was copy pasta that was brought in accidently when I first added in
the build artifacts for cfacter. The digit I am removing here is meant
to correspond to the epoch number of the build. This was required for
facter when we previously messed up the versioning. This is not required
for cfacter. Since this error was only present in the changelog, not the
actual body of the spec file, this change should not impact users.
=> (maint) We are not using an epoch to version cfacter

contrib/cfacter.ps1
Use Ruby 2.1.5, and download specified versions of MinGW. Also fix
building source.
=> (maint) Minor fixes for Powershell setup script

lib/inc/facter/facts/value.hpp
This commit removes the forward declarations for
rapidjson::GenericDocument and rapidjson::Document.
The template paramaters do not match those defined in the current master
branch of rapidjson and are not referenced in value.hpp. Removing them will
allow us to build against master.
=> (maint) Remove unneeded forward declarations

ext/debian/control, ext/debian/rules, ext/redhat/cfacter.spec.erb
With this PR, we're bringing in ruby and ruby-devel to have available during build time. This will let us take advantage of the work done in https://github.com/puppetlabs/cfacter/pull/255 so we can provide the cfacter ruby library, as well as run the full test suite, which will only include the tests against ruby when when a sufficient version of ruby is available.
=> (CFACT-169) Provide ruby during cfacter build time where applicable

appveyor.yml
Use Chocolatey to install mingw and pre-compiled yaml-cpp builds.
=> (maint) Simplify appveyor script

lib/inc/facter/facts/resolvers/filesystem_resolver.hpp, lib/src/facts/linux/filesystem_resolver.cc, lib/src/facts/resolvers/filesystem_resolver.cc, lib/tests/facts/resolvers/filesystem_resolver.cc
The partition label (for GPT partitions) was being reported as the
"label" attribute instead of the expected file system label.
Added "partlabel" attribute to denote the GPT partition label and changed the
"label" attribute to denote the file system label.  This matches what
blkid would output.
=> (CFACT-179) Fix partitions label and add partlabel.

contrib/cfacter.ps1
We need to update the powershell script used for building cfacter on windows to allow us to specify which architecture to build for. In allowing this update, we also need to update this script to fix certain issues when building 32-bit.
=> (CFACT-181) Allow dynamic assignment of variables

lib/src/ruby/ruby_value.cc, lib/tests/fixtures/ruby/uniᐁdir/customfacts™.rb, lib/tests/ruby/ruby.cc
When outputting custom fact values, we were using String#size to get the
size of the strings to write to JSON or to an output stream.
This uses the character size of the string, not the byte size of the
string.  As such, strings were incorrectly truncated when multi-byte
characters were present in the string.
The fix is to use String#bytesize to properly write out all the bytes in
the string.
=> (CFACT-200) Fix output of custom fact values with UTF8 characters.

Extensibility.md, README.md, exe/cfacter.cc, lib/inc/facter/facts/collection.hpp, lib/inc/facter/util/environment.hpp, lib/inc/facter/util/locale.hpp, lib/inc/facter/util/windows/registry.hpp, lib/inc/facter/util/windows/system_error.hpp, lib/inc/facter/util/windows/windows.hpp, lib/inc/facter/util/windows/wmi.hpp, lib/src/facts/collection.cc, lib/src/ruby/fact.cc, lib/src/ruby/module.cc, lib/src/ruby/posix/api.cc, lib/src/ruby/windows/api.cc, lib/src/util/posix/environment.cc, lib/src/util/windows/environment.cc, lib/tests/facts/collection.cc, lib/tests/fixtures/ruby/facterversion.rb, lib/tests/fixtures/ruby/ruby.rb, lib/tests/ruby/ruby.cc, lib/tests/util/environment.cc
Implementing support for setting fact values from environment variables.
Now users can set variables of the form "FACTER_xyz" and a string fact
will be added.  Environment variable facts are the last source of truth
and can override built-in, external, and custom fact values.
This is supported for backwards compatibility with previous versions of
Facter.
=> (CFACT-199) Implement support for setting fact values from environment.

lib/inc/facter/util/environment.hpp, lib/src/facts/collection.cc, lib/src/util/posix/environment.cc, lib/src/util/windows/environment.cc
Build break on Windows: missing include of some headers. Passed Travis because it does a unity build (header dependencies become muddled with unity builds).
Build break on Solaris (and probably OSX): missing declaration of
environ; some platforms don't declare it in unistd.h like they should.
=> (CFACT-199) Fix build breaks on Windows and Solaris.

lib/inc/facter/http/client.hpp, lib/inc/facter/http/request.hpp, lib/inc/facter/http/response.hpp, lib/src/facts/resolvers/ec2_resolver.cc, lib/src/http/client.cc, lib/src/http/request.cc, lib/src/http/response.cc
The EC2 fact resolver did a check for "amazon" in the BIOS vendor in an
attempt to prevent an unnecessary network operation when running
under kvm/xen* hypervisors.  However, the BIOS information is only
available to Hardware Virtual Machines (HVM).  For paravirtual (PV)
instances, the BIOS information is unavailable, causing the EC2 resolver
to skip resolving EC2 facts.
As there is no reliable way to detect if we're running under an EC2
instance without querying the metadata endpoint, the fix is to remove
the BIOS vendor check and gracefully handle failing to query the first
endpoint URL.
=> (CFACT-204) Fix EC2 instance detection for PV instances.

contrib/cfacter.ps1
Use MinGW-w64 builds with win32 threads on Windows, as libpthread isn't
supported on Windows Server 2003.
Also ensure the 32-bit version of MinGW-w64 is first in PATH when building
32-bit if a 64-bit compiler is also installed.
=> (CFACT-166) Use win32 threads on Windows

lib/src/ruby/ruby_value.cc, lib/tests/fixtures/ruby/hash_with_non_string_key.rb, lib/tests/ruby/ruby.cc
If a custom fact resolution returned a hash with a non-string key
(typically a symbol), then Ruby throws an expcetion from
rb_string_value_ptr because the given VALUE is not a string.
The fix is to properly convert the key to a string like we're already
doing for the other formats.
=> (CFACT-206) Fix crash in JSON output for ruby hash with non-string key.

lib/inc/facter/facts/linux/virtualization_resolver.hpp, lib/inc/facter/util/regex.hpp, lib/src/facts/linux/virtualization_resolver.cc
These commits bring parity to how Native Facter resolves the "virtual" fact under Linux.
=> (CFACT-207) Update Linux virtual fact to recent Ruby Facter changes.

ext/build_defaults.yaml
http://builds.delivery.puppetlabs.net/cfacter/1549f785b6a5194976851ca459f07d6f10c57c33/
cfacter on fedora-21-i386
```
[root@ecr00pmcp7bh15f yum.repos.d]# cfacter os
{
architecture => "i686",
family => "RedHat",
hardware => "i386",
name => "Fedora",
release => {
full => "21",
major => "21"
}
}
[root@ecr00pmcp7bh15f yum.repos.d]#
```
cfacter on fedora-21-x86_64
```
[root@smgpgjk80b5jqbt yum.repos.d]# cfacter os
{
architecture => "x86_64",
family => "RedHat",
hardware => "x86_64",
name => "Fedora",
release => {
full => "21",
major => "21"
}
}
[root@smgpgjk80b5jqbt yum.repos.d]#
```
=> (CFACT-210) build cfacter for fedora 21

lib/src/ruby/fact.cc, lib/tests/fixtures/ruby/facterversion.rb, lib/tests/fixtures/ruby/ruby.rb
Ruby Facter uses the same resolution as the "custom" facts do.  As a
result, custom facts looking to override built-in facts must set an
appropriately high weight on their resolutions to supercede the built-in
resolutions.
Native Facter, instead, was treating the built-in values as a "fallback"
if none of the custom fact resolutions resolved to a value.  As a
result, custom facts could easily override built-in facts without having
to set a higher weight.
This fix first checks to see if the custom facts resolutions all have
weight zero; if so, it first checks the built-in collection for the fact
value.  This forces authors of custom facts to set a weight on their
resolution greater than zero to override a built-in fact.
=> (CFACT-201) Fix custom fact resolution to not preempt built-in values.

cmake/FindRuby.cmake
CMake's FindRuby module was missing support for 64-bit Ruby on Windows.
A patch has been submitted; until we move to the patched version, bring
in the patched version.
=> (maint) Source FindRuby

contrib/cfacter.ps1
* Removes test for TEMP, fixed in Chocolatey 0.9.8.29
* Installs 32-bit Ruby if selected.
=> (maint) CFacter build fixes

contrib/cfacter.ps1
Git.install fails unless TEMP is set. Ensure temp is set to a directory
that exists in the Windows bootstrap script.
=> (maint) Fix TEMP variable for git.install

contrib/cfacter.ps1
Fixes the parameter types of the Windows bootstrap script. The
buildSource parameter would always evaluate to true because it's a
string, and strings are always true unless empty.
=> (maint) Fix build script parameter types

CMakeLists.txt
Boost.Nowide headers aren't included in any shipped headers, so don't
ship it.
=> (maint) Disable installing Boost.Nowide headers

appveyor.yml, contrib/cfacter.ps1
Use Myget mirror for Chocolatey packages with installers added to the
Nuget packages to avoid dependencies on other external servers (such as
Sourceforge).
=> (CFACT-214) Use Myget mirror for Chocolatey pkgs

CMakeLists.txt, lib/CMakeLists.txt, lib/inc/facter/facts/windows/networking_resolver.hpp, lib/inc/facter/util/windows/wsa.hpp, lib/src/facts/windows/networking_resolver.cc, lib/src/facts/windows/processor_resolver.cc, lib/src/util/windows/wsa.cc, lib/tests/facts/windows/networking_resolver.cc
Removes DLL dependencies so it can run on Windows Server 2003, and fixes networking and processor facts.
=> (CFACT-166) Add Windows Server 2003 support

ext/debian/rules, ext/redhat/cfacter.spec.erb
A previous commit disabled installing Boost.Nowide. Jenkins
configuration specifically removed those files, which is no longer
necessary and causing builds to fail. Remove the redundant Jenkins
config.
=> (maint) Config build after nowide install disabled

contrib/cfacter.ps1
Chocolatey 0.9.9 will require the -y option for automated install. The
latest release, 0.9.8.33, adds it as an option and was released this
morning.
=> (maint) Prepare for Choco.exe 0.9.9

contrib/cfacter.ps1
Provide debugging output from Chocolatey, so when things go wrong, it is easier
to determine why that is the case e.g. not finding packages.
Move the default set of args passed to all choco commands to an array to reduce change and DRY things up a bit.
=> (maint) Choco improvements

ext/build_defaults.yaml
This commit adds Debian stable-amd64 and stable-i386 as build targets
for cfacter.
http://builds.delivery.puppetlabs.net/cfacter/37b60cb7e2c56e8b96b4901b2feb358aec2a1d4d/
cfacter on stable-i386
```
root@qqg8fpknelwty4z:/etc/apt/sources.list.d# cfacter os
{
architecture => "i686",
distro => {
codename => "wheezy",
description => "Debian GNU/Linux 7.4 (wheezy)",
id => "Debian",
release => {
full => "7.4",
major => "7",
minor => "4"
}
},
family => "Debian",
hardware => "i386",
name => "Debian",
release => {
full => "7.4",
major => "7",
minor => "4"
}
}
```
cfacter on stable-amd64
```
root@o3fpvj26vcgr6uj:/etc/apt/sources.list.d# cfacter os
{
architecture => "x86_64",
distro => {
codename => "wheezy",
description => "Debian GNU/Linux 7.4 (wheezy)",
id => "Debian",
release => {
full => "7.4", …
```
=> (CFACT-221) Build cfacter for stable

contrib/cfacter.ps1
Writes git describe --long to a bin/VERSION file during Windows builds for
packaging to pick up. Put into bin to simplify packaging pipeline
changes.
=> (CFACT-220) Write git describe to VERSION

appveyor.yml, lib/src/execution/windows/execution.cc, lib/tests/facts/external/windows/execution_resolver.cc, lib/tests/facts/windows/collection.cc, lib/tests/fixtures/facts/external/windows/execution/ruby_script.rb
A Ruby script can be used as an external fact. On Windows, that doesn't
work if you try to invoke the script using CreateProcess; an execution
environment that knows about Ruby is required. Wraps external facts in a
shell to ensure scripts are run in a usable environment.
=> (CFACT-219) Fix executing external ruby fact

.editorconfig
If the user adds an editorconfig plugin to their editor or IDE,
editorconfig auto-applies the correct coding style.
=> (maint) support consistent coding style across users

lib/inc/facter/facts/linux/operating_system_resolver.hpp, lib/inc/facter/facts/linux/release_file.hpp, lib/inc/facter/facts/os.hpp, lib/inc/facter/facts/os_family.hpp, lib/src/facts/linux/operating_system_resolver.cc, lib/src/facts/resolvers/operating_system_resolver.cc
This commit ports https://github.com/puppetlabs/facter/pull/845
to native facter.
=> (CFACT-215) use /etc/os-release to identify CoreOS

contrib/cfacter.ps1
- Previously, the output of `git describe` was written directly to
`bin/VERSION`.  Unfortunately, this was resulting in a UCS-2 file
with a BOM that our Ruby 1.8 based build environment could not easily
parse.
To make life easier, capture the command output in PowerShell, and
use the Out-File cmdlet to force an ASCII file be written instead.
Consumers of this file will no longer need to jump through hoops.
Verified in both Ruby 1.8.7 and Ruby 2.1.5 that File.read('VERSION')
will properly return this results of this file.
=> (CFACT-220) cfacter.ps1 VERSION file in ASCII

exe/cfacter.cc, lib/inc/facter/logging/logging.hpp, lib/src/logging/logging.cc, lib/tests/logging/logging.cc
Previously, cfacter would only exit with a failure code if an
exception managed to bubble all the way up to main. This meant that it
was impossible to tell without parsing the log output whether an error
had actually been encountered.
This adds functionality to the logger to track when an error or fatal
message is logged, and updates the cfacter main to use this
functionality to return a failure code when such a message has been
loged.
=> (CFACT-217) Exit with a failure code when an error has been logged

CMakeLists.txt, lib/src/facts/linux/virtualization_resolver.cc
Add a compile-time define to specify a preferred binary lookup directory
that will be prioritized over PATH. Required for packages (AIO) that
want to specify specific binaries that should override the environment.
=> (CFACT-213) Allow compile-time preferred PATH

CMakeLists.txt, lib/src/ruby/posix/api.cc, lib/src/ruby/windows/api.cc
Allow libruby location to be set at compile-time, so we can specify
which Ruby should be used as part of a package (AIO).
=> (CFACT-74) Allow compile-time setting libruby loc

lib/inc/facter/facts/fact.hpp, lib/inc/facter/facts/resolvers/dmi_resolver.hpp, lib/src/facts/linux/dmi_resolver.cc, lib/src/facts/resolvers/dmi_resolver.cc, lib/src/facts/solaris/dmi_resolver.cc, lib/tests/facts/resolvers/dmi_resolver.cc
In native Facter, the former 'uuid' top-level fact was renamed to 'productuuid.'
To maintain backwards compatibility, this commit reverts that change so
that 'uuid' is once again the top-level fact name.
Note that top-level flat facts are now considered legacy facts, since the
default output of native facter is fully structured. This change does
not affect the 'dmi' structured fact, or the 'dmi.product.uuid' fact
within it. It can only be accessed directly by invoking cfacter with
'uuid' as an argument.
=> (CFACT-126) Rename 'productuuid' top level flat fact to 'uuid'

lib/src/facts/posix/collection.cc
Updating the default path for external facts from
/opt/puppetlabs/agent/facts.d to /opt/puppetlabs/facter/facts.d per
recent AIO changes.
=> (CFACT-228) Update default path for external facts.

lib/src/facts/linux/operating_system_resolver.cc
On Debian, Gentoo, kFreeBSD, and Gentoo, the architecture fact should
resolve to "amd64" for "x86_64".  On Gentoo, it should resolve to "x86"
for "i386".  However, the code was attempting to resolve the
hardwaremodel fact to these values instead.  Additionally, the check for
the distro name occurs before it was being populated.
The fix is to move the check to after the distro name is being resolved
and change the assignment to the architecture fact.
=> (CFACT-230) Fix architecture fact resolution on certain Linux distros.

lib/inc/facter/util/windows/wmi.hpp, lib/src/facts/windows/processor_resolver.cc
Prior to this commit, the processors.isa and hardwareisa facts were
not being populated in Windows.
This commit adds the necessary logic to query WMI for "Architecture"
and transform the returned numerical ID into a string representing the
processor type.
Details on the translation from ID to processor type can be found here:
https://msdn.microsoft.com/en-us/library/aa394373%28v=vs.85%29.aspx
=> (CFACT-231) Resolve processors.isa and hardwareisa in Windows

lib/docs/generate.rb, lib/docs/template.erb, scripts/travis_target.sh
Adding lib/docs/generate.rb (usage: ruby generate.rb > facts.md).
This script will transform the schema file into a markdown and extract
the name, purpose, resolutions, and caveats for each fact.
=> (CFACT-152) Add script to generate fact documentation markdown.

CMakeLists.txt
Previously we got some CMake options as part of the leatherman cflags
include. This was too late in the CMake code to affect find_package
calls that we expected to respect these options. Specifically,
BOOST_STATIC was doing nothing of note.
We now bring in the options fairly early (after we set up our own
options, but before we find any packages)
=> (CFACT-235) Pull in leatherman options earlier in CMakeLists.txt

lib/inc/facter/ruby/api.hpp, lib/src/ruby/api.cc, lib/src/ruby/confine.cc, lib/src/ruby/resolution.cc, lib/tests/fixtures/ruby/range_confine.rb, lib/tests/fixtures/ruby/regexp_confine.rb, lib/tests/ruby/ruby.cc
In previous versions of Facter, confine values for facts could utilize
regular expressions and ranges. Currently, native Facter only allows
true, false, Symbols, Strings, and Arrays of Strings/Symbols for
custom facts.
This commit updates native Facter to allow regular expressions and
ranges in confine statements in order to preserve backwards
compatibility with older versions of Facter.
=> (CFACT-233) Allow regexps and ranges for custom fact confine values

lib/inc/facter/execution/execution.hpp, lib/inc/facter/ruby/api.hpp, lib/src/execution/windows/execution.cc, lib/src/facts/external/windows/powershell_resolver.cc, lib/src/ruby/api.cc, lib/src/ruby/posix/api.cc, lib/src/ruby/windows/api.cc, lib/tests/execution/windows/execution.cc, lib/tests/fixtures/ruby/exec.rb, lib/tests/fixtures/ruby/simple_command.rb, lib/tests/ruby/ruby.cc
Without this change, lookup for libruby would search based on the
location of Ruby found on PATH. This required special handling for
wrappers like rbenv.
Change lookup to query Ruby's RbConfig for the location of its dynamic
library instead of searching the filesystem.
Also rewrite the execute functions' argument handling for Windows. Without
this change arguments that needed to be quoted due to spaces didn't work.
Automatically quotes arguments as needed for consistency with the POSIX
behavior, requiring that separate arguments are passed as separate strings.
=> (CFACT-211) Query Ruby for correct library location

appveyor.yml
Use pre-installed Ruby and 7-Zip on AppVeyor to reduce build time.
=> (maint) Use pre-installed software on AppVeyor

exe/CMakeLists.txt, lib/CMakeLists.txt
Removing --exclude-libs=ALL on Linux because this prevents libstdc++
from working when statically linked.
This also prevents all of libfacter's dependencies from getting passed
to the linker when linking cfacter.
=> (CFACT-83) Stop excluding all symbols from libfacter on Linux.

lib/inc/facter/execution/execution.hpp, lib/inc/internal/execution/execution.hpp, lib/src/execution/posix/execution.cc, lib/src/execution/windows/execution.cc
The facter::execution::process_stream function is meant to be an
internal function used by other functions in the execution namespace,
but it was included in the public header (and therefore exported).
This commit moves it to an "internal" header.
=> (CFACT-83) Make facter::execution::process_stream internal.

CONTRIBUTING.md
Hi, 
the CONTRIBUTING.md mentioned a file named `schema/facter.json` but the file is named `schema/facter.yaml`. 
Best wishes,
Matthias
=> (doc) Fix wrong filename (schema/facter.yaml vs. schema/facter.json)

.travis.yml, contrib/dockerfiles/travis-cpp-builder/Dockerfile
Updates the Dockerfile used to configure a Travis-equivalent builder to
build cppcheck 1.68. That version of cppcheck fixes errors with unused
return values in variadic templates.
Without this change, we run into false errors in cppcheck about unused
return values when they're passed to variadic templates. cppcheck 1.68
fixes that issue.
=> (maint) Update cppcheck to 1.68

CONTRIBUTING.md
Hi *,
this pull-request add a notice about the `make cpplint` target in CONTRIBUTING.md.
best wishes,
Matthias
=> (doc) Mention the cpplint target to check code formating.

lib/CMakeLists.txt, lib/inc/facter/execution/execution.hpp, lib/inc/facter/util/scope_exit.hpp, lib/inc/facter/util/scoped_resource.hpp, lib/inc/internal/execution/execution.hpp, lib/src/execution/execution.cc, lib/src/execution/posix/execution.cc, lib/src/execution/windows/execution.cc, lib/src/util/scope_exit.cc, lib/src/util/windows/system_error.cc, lib/tests/execution/posix/execution.cc, lib/tests/execution/windows/execution.cc, lib/tests/fixtures/execution/sleep.sh
Implementing a timeout for command execution on Windows and POSIX operating systems.
This feature will enable us to timeout command executions that are known to hang Facter (such as `prtdiag` on Solaris).
=> (CFACT-253) Implement timeout option for command execution.

ext/debian/rules
Debian build VMs are occasionally running out of memory with the message
`virtual memory exhausted: Cannot allocate memory`. This is likely
because compiling C++ is a memory hog, and machines don't have enough
memory allocated to cover a build for each core.
Hard-code the number of parallel procs to 2. Most of our debian builders
use 4GB of memory, and more than 2 processes are likely to exhaust that
at some point.
=> (maint) Reduce build procs to avoid out-of-memory

lib/inc/facter/execution/execution.hpp, lib/src/execution/execution.cc, lib/src/execution/posix/execution.cc, lib/src/execution/windows/execution.cc, lib/tests/execution/posix/execution.cc
Fixing POSIX command timeout to properly kill the entire child process
tree rather than just the child.  This will kill other processes spawned
from the child process.
=> (CFACT-263) Fix child process cleanup for POSIX command timeout.

lib/src/execution/windows/execution.cc, lib/tests/execution/windows/execution.cc
Command timeout for Windows systems does not properly kill the entire
child process tree, only the process directly spawned by libfacter.
Modify the unit test to demonstrate this problem by calling ruby from a
command shell, so we have a two-level process tree. With that modification
and without the rest of this commit, ruby.exe is not terminated and takes
the unit tests are hung for 60 seconds.
Create a job object and associate the spawned process with it, then use
TerminateJobObject to kill the entire process tree.
=> (CFACT-264) Execution timeout on Windows kills process tree

contrib/cfacter.ps1
Without this change, packaging on Windows initializes the submodules on
the master branch, no matter what ref is requested.
Do submodule init and update after changing to the requested branch, to
ensure the correct submodules are initialized and at the right ref.
We are currently running into some errors where building native facter
will throw errors, but the script will continue to run. This isn't good,
especially because it means we ship an incomplete archive. This commit
is an attempt at having the native facter build script fail in a
consistent way when things go wrong.
=> (maint) Fix submodule init and failure mode in Windows packaging
